# serverless.yml

service: recipes

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: recipes.web.app.app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  profile: recipes

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
